from ..activations import (
    SGELU,
    LaLU,
    CaLU,
    TripleStateSwish,
    GeneralizedSwish,
    ExponentialSwish,
    SigmoidDerivative,
    Gish,
    Logish,
    LogLogish,
    ExpExpish,
    SelfArctan,
    ParametricLogish,
    Phish,
    Suish,
    TSReLU,
    TBSReLU,
    LogSigmoid,
    ShiftedReLU,
    RReLU,
    SoftsignRReLU,
    RandomizedSlopedReLU,
    NoisyReLU,
    SineReLU,
    MinSin,
    AOAF,
    DLReLU,
    ExponentialDLReLU,
    ShiLU,
)


class StochasticClassifier:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._activation_pool = [
            SGELU,
            LaLU,
            CaLU,
            TripleStateSwish,
            GeneralizedSwish,
            ExponentialSwish,
            SigmoidDerivative,
            Gish,
            Logish,
            LogLogish,
            ExpExpish,
            SelfArctan,
            ParametricLogish,
            Phish,
            Suish,
            TSReLU,
            TBSReLU,
            LogSigmoid,
            ShiftedReLU,
            RReLU,
            SoftsignRReLU,
            RandomizedSlopedReLU,
            NoisyReLU,
            SineReLU,
            MinSin,
            AOAF,
            DLReLU,
            ExponentialDLReLU,
            ShiLU,
        ]
